package com.macbury.unamed.level;

public enum Shadow {
  SHADOW_NEED_TO_REFRESH, SHADOW_NONE, SHADOW_CORNER_TOP_LEFT, SHADOW_LEFT, SHADOW_TOP, SHADOW_CORNER_BOTTOM_LEFT, SHADOW_LEFT_ENDING, SHADOW_TOP_ENDING
}
